=== Worthwelle/Alphonic/resources/alphabet_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "https://www.github.com/worthwelle/alphony/resources/schema.json",
  "properties": {
    "code": {
      "type": "string"
    },
    "title": {
      "type": [
        "object",
        "string"
      ],
      "patternProperties": {
        "^.*$": {
          "type": [
            "string",
            "array"
          ]
        }
      }
    },
    "description": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "case_sensitive": {
      "type": "boolean"
    },
    "alphabets": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": [
            "object",
            "string"
          ],
          "patternProperties": {
            "^.*$": {
              "type": [
                "string",
                "array"
              ],
              "maxItems": 2
            }
          }
        }
      }
    }
  },
  "required": [
    "code",
    "title",
    "alphabets"
  ]
}

=== Worthwelle/Alphonic/alphabets/uecu1920.json
{
    "code": "UECU1920",
    "title": {
        "en": "Universal Electrical Communications Union (1920)"
    },
    "description": "The phonetic alphabet laid forth in Appendix 14 (International Radiotelephone Procedure) of the Draft of Convention and Regulations put forward by the Universal Electrical Communications Union in 1920.",
    "source": "https://books.google.com/books?id=OVgNAAAAYAAJ&pg=PA101",
    "alphabets": {
        "en": {
            "A": "Argentine",
            "B": "Brussels",
            "C": "Canada",
            "D": "Damascus",
            "E": "Ecuador",
            "F": "France",
            "G": "Greece",
            "H": "Hanover",
            "I": "Italy",
            "J": "Japan",
            "K": "Khartoum",
            "L": "Lima",
            "M": "Madrid",
            "N": "Nancy",
            "O": "Ostend",
            "P": "Paris",
            "Q": "Quebec",
            "R": "Rome",
            "S": "Sardinia",
            "T": "Tokio",
            "U": "Uruguay",
            "V": "Victoria",
            "W": "Washington",
            "X": "Xaintrie",
            "Y": "Yokohama",
            "Z": "Zanzibar"
        },
        "fr": {
            "A": "Argentina",
            "B": "Bruxelles",
            "C": "Canada",
            "D": "Damas",
            "E": "Ecuador",
            "F": "France",
            "G": "Grèce",
            "H": "Hanovre",
            "I": "Italie",
            "J": "Japon",
            "K": "Khartoum",
            "L": "Lima",
            "M": "Madrid",
            "N": "Nancy",
            "O": "Ostende",
            "P": "Paris",
            "Q": "Québec",
            "R": "Rome",
            "S": "Sardaigne",
            "T": "Tokio",
            "U": "Uruguay",
            "V": "Victoria",
            "W": "Washington",
            "X": "Xaintrie",
            "Y": "Yokohama",
            "Z": "Zanzibar"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usnww2.json
{
    "code": "USNWW2",
    "title": {
        "en": "U.S. Navy World War II"
    },
    "description": "",
    "source": "https://en.wikipedia.org/wiki/Allied_military_phonetic_spelling_alphabets#cite_note-19",
    "alphabets": {
        "en": {
            "A": "Afirm",
            "B": "Baker",
            "C": "Charlie",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "How",
            "I": "Int",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Negat",
            "O": "Option",
            "P": "Prep",
            "Q": "Queen",
            "R": "Roger",
            "S": "Sugar",
            "T": "Tare",
            "U": "Uncle",
            "V": "Victor",
            "W": "William",
            "X": "Xray",
            "Y": "Yoke",
            "Z": "Zebra"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usas1919.json
{
    "code": "USAS1919",
    "title": {
        "en": "U.S. Air Service (1919)"
    },
    "description": "The phonetic alphabet used by the U.S. Air Service in 1919.",
    "source": "https://www.governmentattic.org/4docs/ICAO-WordSpellingAlphabet_1959.pdf",
    "alphabets": {
        "en": {
            "A": "Able",
            "B": "Boy",
            "C": "Cast",
            "D": "Dock",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "Have",
            "I": "Item",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Nan",
            "O": "Oble",
            "P": "Pup",
            "Q": "Quack",
            "R": "Rush",
            "S": "Sail",
            "T": "Tare",
            "U": "Unit",
            "V": "Vice",
            "W": "Watch",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zed"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usn1913.json
{
    "code": "Alphonic-USN1913",
    "title": {
        "en": "U.S. Navy (1913-1926)"
    },
    "description": "The phonetic alphabet used by the U.S. Navy between 1913 and 1926.",
    "source": "https://en.wikipedia.org/wiki/Allied_military_phonetic_spelling_alphabets",
    "alphabets": {
        "en": {
            "A": "Able",
            "B": "Boy",
            "C": "Cast",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "Have",
            "I": "Item",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Nan",
            "O": "Oboe",
            "P": "Pup",
            "Q": "Quack",
            "R": "Rush",
            "S": "Sail",
            "T": "Tare",
            "U": "Unit",
            "V": "Vice",
            "W": "Watch",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zed"
        }
    }
}

=== Worthwelle/Alphonic/resources/test_alphabets/valid_nato.json
{
    "code": "NATO",
    "title": {
        "en": [
            "NATO Phonetic Alphabet",
            "International Radiotelephony Spelling Alphabet",
            "ICAO phonetic alphabet"
        ]
    },
    "description": "The most widely used radiotelephone spelling alphabet. It is officially the International Radiotelephony Spelling Alphabet, and also commonly known as the ICAO phonetic alphabet, with a variation officially known as the ITU phonetic alphabet and figure code.",
    "source": "https://www.icao.int/Pages/AlphabetRadiotelephony.aspx",
    "alphabets": {
        "en": {
            "A": "Alfa",
            "B": "Bravo",
            "C": "Charlie",
            "D": "Delta",
            "E": "Echo",
            "F": "Foxtrot",
            "G": "Golf",
            "H": "Hotel",
            "I": "India",
            "J": "Juliett",
            "K": "Kilo",
            "L": "Lima",
            "M": "Mike",
            "N": "November",
            "O": "Oscar",
            "P": "Papa",
            "Q": "Quebec",
            "R": "Romeo",
            "S": "Sierra",
            "T": "Tango",
            "U": "Uniform",
            "V": "Victor",
            "W": "Whiskey",
            "X": "Xray",
            "Y": "Yankee",
            "Z": "Zulu",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Niner",
            "0": "Zero"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/apco1967.json
{
    "code": "Alphonic-APCO1967",
    "title": {
        "en": "Association of Public-Safety Communications Officials-International Project 2 (1967)"
    },
    "description": "The phonetic alphabet developed by the Association of Public-Safety Communications Officials-International in 1967 for use by police departments and emergency service agencies.",
    "source": "https://archive.org/details/nationaltraining025505mbp",
    "alphabets": {
        "en": {
            "A": "Adam",
            "B": "Boy",
            "C": "Charles",
            "D": "David",
            "E": "Edward",
            "F": "Frank",
            "G": "George",
            "H": "Henry",
            "I": "Ida",
            "J": "John",
            "K": "King",
            "L": "Lincoln",
            "M": "Mary",
            "N": "Nora",
            "O": "Ocean",
            "P": "Paul",
            "Q": "Queen",
            "R": "Robert",
            "S": "Sam",
            "T": "Tom",
            "U": "Union",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Young",
            "Z": "Zebra",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Nine",
            "0": "Zero"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/ircc1938.json
{
    "code": "IRCC1938",
    "title": {
        "en": "International Radiocommunication Conference (Cairo, 1938)"
    },
    "description": "The phonetic alphabet laid forth in Appendix 14 (Procedure in the Service of Low-Power Mobile Radiotelephone Stations) of the General Radiocommunication Regulations put forward by the International Radiocommunication Conference in 1938.",
    "source": "http://search.itu.int/history/HistoryDigitalCollectionDocLibrary/1.6.48.en.100.pdf",
    "alphabets": {
        "en": {
            "A": "Amsterdam",
            "B": "Baltimore",
            "C": "Casablanca",
            "D": "Danemark",
            "E": "Edison",
            "F": "Florida",
            "G": "Gallipoli",
            "H": "Havana",
            "I": "Italia",
            "J": "Jérusalem",
            "K": "Kilogramme",
            "L": "Liverpool",
            "M": "Madagascar",
            "N": "New-York",
            "O": "Oslo",
            "P": "Paris",
            "Q": "Québec",
            "R": "Roma",
            "S": "Santiago",
            "T": "Tripoli",
            "U": "Upsala",
            "V": "Valencia",
            "W": "Washington",
            "X": "Xanthippe",
            "Y": "Yokohama",
            "Z": "Zürich",
            "0": "Zero",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Nine",
            ",": "Comma",
            "/": "Fraction bar",
            ".": "Full stop",
            "BREAK": "Break signal"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usafm245-1941.json
{
    "code": "USAFM245-1941",
    "title": {
        "en": "U.S. Army Field Manual 24-5 (1941-1943)"
    },
    "description": "The phonetic alphabet used by the U.S. Army between 1941 and 1943 according to Field Manual 24-5. This alphabet was used only for joint Army/Navy operations.",
    "source": "https://archive.org/details/Fm24-51942",
    "alphabets": {
        "en": {
            "A": "Afirm",
            "B": "Baker",
            "C": "Cast",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "Hypo",
            "I": "Interrogatory",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Negat",
            "O": "Option",
            "P": "Prep",
            "Q": "Queen",
            "R": "Roger",
            "S": "Sail",
            "T": "Tare",
            "U": "Unit",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zed",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Nine",
            "0": "Zero"
        }
    }
}
