=== Worthwelle/Alphonic/resources/alphabet_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "https://www.github.com/worthwelle/alphony/resources/schema.json",
  "properties": {
    "code": {
      "type": "string"
    },
    "title": {
      "type": [
        "object",
        "string"
      ],
      "patternProperties": {
        "^.*$": {
          "type": [
            "string",
            "array"
          ]
        }
      }
    },
    "description": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "case_sensitive": {
      "type": "boolean"
    },
    "alphabets": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": [
            "object",
            "string"
          ],
          "patternProperties": {
            "^.*$": {
              "type": [
                "string",
                "array"
              ],
              "maxItems": 2
            }
          }
        }
      }
    }
  },
  "required": [
    "code",
    "title",
    "alphabets"
  ]
}

=== Worthwelle/Alphonic/alphabets/usjan1941a.json
{
    "code": "USJAN1941A",
    "title": {
        "en": "U.S. Joint Army/Navy variant (1941-1943)"
    },
    "description": "An alternate of the phonetic alphabet used by the U.S. Army and Navy from 1941 to 1943.",
    "source": "http://www.bckelk.ukfsn.org/able.html",
    "alphabets": {
        "en": {
            "A": "Able",
            "B": "Baker",
            "C": "Charlie",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "How",
            "I": "Interrogatory",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Nan",
            "O": "Oboe",
            "P": "Peter",
            "Q": "Queen",
            "R": "Roger",
            "S": "Sugar",
            "T": "Tare",
            "U": "Uncle",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zebra",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Nine",
            "0": "Zero"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usasb1916.json
{
    "code": "USASB1916",
    "title": {
        "en": "U.S. Army Signal Book (1916-1939)"
    },
    "description": "The phonetic alphabet used by the U.S. Army between 1916 and 1939.",
    "source": "https://archive.org/details/SignalBook1916",
    "alphabets": {
        "en": {
            "A": "Able",
            "B": "Boy",
            "C": "Cast",
            "D": "Dock",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "Have",
            "I": "Item",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Nan",
            "O": "Opal",
            "P": "Pup",
            "Q": "Quack",
            "R": "Rush",
            "S": "Sail",
            "T": "Tare",
            "U": "Unit",
            "V": "Vice",
            "W": "Watch",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zed"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/ccbusuk1943.json
{
    "code": "CCBUSUK1943",
    "title": {
        "en": "Combined Communications Board (1943)"
    },
    "description": "",
    "source": "http://www.n7cfo.com/tgph/Dwnlds/sigcorps/FM24-12.pdf",
    "alphabets": {
        "en": {
            "A": "Able",
            "B": "Baker",
            "C": "Charlie",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "How",
            "I": "Item",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Nan",
            "O": "Oboe",
            "P": "Peter",
            "Q": "Queen",
            "R": "Roger",
            "S": "Sugar",
            "T": "Tare",
            "U": "Uncle",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zebra",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Niner",
            "0": "Zero"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/ccir-ican1932.json
{
    "code": "Alphonic-CCIR-ICAN1932",
    "title": {
        "en": "General Radiocommunication and Additional Regulations (CCIR/ICAN, 1932)"
    },
    "description": "The phonetic alphabet laid forth in Appendix 12 (Procedure in the service of low-power mobile radiotelephone stations) of the General Radiocommunication  and Additional Regulations put forward by the CCIR/ICAN in 1932.",
    "source": "http://search.itu.int/history/HistoryDigitalCollectionDocLibrary/1.5.48.en.100.pdf",
    "alphabets": {
        "en": {
            "_num_prefix": "As a number",
            "_num_postfix": "As a number",
            "A": "Amsterdam",
            "B": "Baltimore",
            "C": "Casablanca",
            "D": "Danemark",
            "E": "Edison",
            "F": "Florida",
            "G": "Gallipoli",
            "H": "Havana",
            "I": "Italia",
            "J": "Jérusalem",
            "K": "Kilogramme",
            "L": "Liverpool",
            "M": "Madagascar",
            "N": "New York",
            "O": "Oslo",
            "P": "Paris",
            "Q": "Québec",
            "R": "Roma",
            "S": "Santiago",
            "T": "Tripoli",
            "U": "Upsala",
            "V": "Valencia",
            "W": "Washington",
            "X": "Xanthippe",
            "Y": "Yokohama",
            "Z": "Zürich",
            "0": "Zero",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Nine",
            ",": "Comma",
            "/": "Fraction bar"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/wu1928.json
{
    "code": "WU1928",
    "title": {
        "en": [
            "American Association of Railroads (1932)",
            "Western Union (~1928)"
        ]
    },
    "description": "",
    "source": "https://www.governmentattic.org/4docs/ICAO-WordSpellingAlphabet_1959.pdf",
    "alphabets": {
        "en": {
            "A": "Adams",
            "B": "Boston",
            "C": "Chicago",
            "D": "Denver",
            "E": "Edward",
            "F": "Frank",
            "G": "George",
            "H": "Henry",
            "I": "Ida",
            "J": "John",
            "K": "King",
            "L": "Lincoln",
            "M": "Mary",
            "N": "New York",
            "O": "Ocean",
            "P": "Peter",
            "Q": "Queen",
            "R": "Robert",
            "S": "Sugar",
            "T": "Thomas",
            "U": "Union",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Young",
            "Z": "Zero"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/ccir1927.json
{
    "code": "CCIR1927",
    "title": {
        "en": "General Radiotelegraph Regulations (1927)",
        "fr": "Réglement général et additionnel des radiocommunications (1927)"
    },
    "description": "The phonetic alphabet laid forth in Appendix 1 (International Radiotelephone Procedure) of the General Radiotelegraph Regulations put forward by the International Radiotelegraph Convention in 1927.",
    "source": "http://handle.itu.int/11.1004/020.1000/1.4",
    "alphabets": {
        "en": {
            "A": "Amsterdam",
            "B": "Baltimore",
            "C": "Canada",
            "D": "Denmark",
            "E": "Eddystone",
            "F": "Francisco",
            "G": "Gibraltar",
            "H": "Hanover",
            "I": "Italy",
            "J": "Jerusalem",
            "K": "Kimberley",
            "L": "Liverpool",
            "M": "Madagascar",
            "N": "Neufchatel",
            "O": "Ontario",
            "P": "Portugal",
            "Q": "Quebec",
            "R": "Rivoli",
            "S": "Santiago",
            "T": "Tokio",
            "U": "Uruguay",
            "V": "Victoria",
            "W": "Washington",
            "X": "Xantippe",
            "Y": "Yokohama",
            "Z": "Zululand"
        },
        "fr": {
            "A": "Amsterdam",
            "B": "Baltimore",
            "C": "Canada",
            "D": "Danemark",
            "E": "Eddiston",
            "F": "Francisco",
            "G": "Gibraltar",
            "H": "Hanovre",
            "I": "Italie",
            "J": "Jérusalem",
            "K": "Kimberley",
            "L": "Liverpool",
            "M": "Madagascar",
            "N": "Neuchâtel",
            "O": "Ontario",
            "P": "Portugal",
            "Q": "Québec",
            "R": "Rivoli",
            "S": "Santiago",
            "T": "Tokio",
            "U": "Uruguay",
            "V": "Victoria",
            "W": "Washington",
            "X": "Xanthippe",
            "Y": "Yokohama",
            "Z": "Zoulouland"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/nato1956.json
{
    "code": "Alphonic-NATO1956",
    "title": {
        "en": "NATO Phonetic Alphabet (Jan 1 - Feb 29, 1956)"
    },
    "description": "The NATO phonetic spelling alphabet was first adopted on January 1, 1956, while the ICAO radiotelephony spelling alphabet was still undergoing final changes.",
    "source": "http://archives.nato.int/uploads/r/null/1/2/126367/SGM-0217-55_ENG_PDP.pdf",
    "alphabets": {
        "en": {
            "A": "Alfa",
            "B": "Bravo",
            "C": "Charlie",
            "D": "Delta",
            "E": "Echo",
            "F": "Foxtrot",
            "G": "Golf",
            "H": "Hotel",
            "I": "India",
            "J": "Juliett",
            "K": "Kilo",
            "L": "Lima",
            "M": "Mike",
            "N": "Nectar",
            "O": "Oscar",
            "P": "Papa",
            "Q": "Quebec",
            "R": "Romeo",
            "S": "Sierra",
            "T": "Tango",
            "U": "Uniform",
            "V": "Victor",
            "W": "Whiskey",
            "X": "X-ray",
            "Y": "Yankee",
            "Z": "Zulu"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/irc1947.json
{
    "code": "Alphonic-IRC1947",
    "title": {
        "en": "Radio Regulations and Additional Radio Regulations (Atlantic City, 1947)",
        "fr": "Réglement et réglement additionnel des radiocommunications (Atlantic City, 1947)",
        "es": "Reglamento y Reglamento Adicional de Radiocomunicaciones (Atlantic City, 1947)",
        "zh": "無線電法規和附加無線電法規（一九四七年，大西洋城）"
    },
    "description": "The phonetic alphabet laid forth in Appendix 11 (Procedure in the Mobile Radiotelephone Service) of the Radio Regulations put forward by the International Radio Conference in Atlantic City, 1947.",
    "source": "http://handle.itu.int/11.1004/020.1000/4.62",
    "alphabets": {
        "en": {
            "A": "Amsterdam",
            "B": "Baltimore",
            "C": "Casablanca",
            "D": "Danemark",
            "E": "Edison",
            "F": "Florida",
            "G": "Gallipoli",
            "H": "Havana",
            "I": "Italia",
            "J": "Jerusalem",
            "K": "Kilogramme",
            "L": "Liverpool",
            "M": "Madagascar",
            "N": "New York",
            "O": "Oslo",
            "P": "Paris",
            "Q": "Quebec",
            "R": "Roma",
            "S": "Santiago",
            "T": "Tripoli",
            "U": "Upsala",
            "V": "Valencia",
            "W": "Washington",
            "X": "Xantippe",
            "Y": "Yokohama",
            "Z": "Zurich",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Nine",
            "0": "Zero",
            ",": "Comma",
            "/": "Fraction bar",
            "BREAK": "Break signal",
            ".": "Period"
        },
        "fr": {
            "A": "Amsterdam",
            "B": "Baltimore",
            "C": "Casablanca",
            "D": "Danemark",
            "E": "Edison",
            "F": "Florida",
            "G": "Gallipoli",
            "H": "Havana",
            "I": "Italia",
            "J": "Jérusalem",
            "K": "Kilogramme",
            "L": "Liverpool",
            "M": "Madagascar",
            "N": "New York",
            "O": "Oslo",
            "P": "Paris",
            "Q": "Québec",
            "R": "Roma",
            "S": "Santiago",
            "T": "Tripoli",
            "U": "Upsala",
            "V": "Valencia",
            "W": "Washington",
            "X": "Xantippe",
            "Y": "Yokohama",
            "Z": "Zurich",
            "1": "Une",
            "2": "Deux",
            "3": "Trois",
            "4": "Quatre",
            "5": "Cinq",
            "6": "Six",
            "7": "Sept",
            "8": "Huit",
            "9": "Neuf",
            "0": "Zéro",
            ",": "Virgule",
            "/": "Barre de fraction",
            "BREAK": "Signal séparatif",
            ".": "Point"
        },
        "es": {
            "A": "Amsterdam",
            "B": "Baltimore",
            "C": "Casablanca",
            "D": "Dinamarca",
            "E": "Edison",
            "F": "Florida",
            "G": "Gallípoli",
            "H": "Habana",
            "I": "Italia",
            "J": "Jerusalén",
            "K": "Kilogramo",
            "L": "Liverpool",
            "M": "Madagascar",
            "N": "Nueva York",
            "O": "Oslo",
            "P": "París",
            "Q": "Quebec",
            "R": "Roma",
            "S": "Santiago",
            "T": "Trípoli",
            "U": "Upsala",
            "V": "Valencia",
            "W": "Wáshington",
            "X": "Xantippe",
            "Y": "Yokohama",
            "Z": "Zurich",
            "1": "Uno",
            "2": "Dos",
            "3": "Tres",
            "4": "Cuatro",
            "5": "Cinco",
            "6": "Seis",
            "7": "Siete",
            "8": "Ocho",
            "9": "Nueve",
            "0": "Cero",
            ",": "Coma",
            "/": "Barra de fracción",
            "BREAK": "Señal de separación",
            ".": "Punto"
        },
        "zh_HANT": {
            "A": "Amsterdam",
            "B": "Baltimore",
            "C": "Casablanca",
            "D": "Danemark",
            "E": "Edison",
            "F": "Florida",
            "G": "Gallipoli",
            "H": "Havana",
            "I": "Italia",
            "J": "Jerusalem",
            "K": "Kilogramme",
            "L": "Liverpool",
            "M": "Madagascar",
            "N": "New York",
            "O": "Oslo",
            "P": "Paris",
            "Q": "Quebec",
            "R": "Roma",
            "S": "Santiago",
            "T": "Tripoli",
            "U": "Upsala",
            "V": "Valencia",
            "W": "Washington",
            "X": "Xantippe",
            "Y": "Yokohama",
            "Z": "Zurich",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Nine",
            "0": "Zero",
            ",": "進點",
            "/": "分數针劃",
            "BREAK": "TODO_BREAK",
            ".": "TODO_POINT"
        }
    }
}
