=== Worthwelle/Alphonic/resources/alphabet_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "https://www.github.com/worthwelle/alphony/resources/schema.json",
  "properties": {
    "code": {
      "type": "string"
    },
    "title": {
      "type": [
        "object",
        "string"
      ],
      "patternProperties": {
        "^.*$": {
          "type": [
            "string",
            "array"
          ]
        }
      }
    },
    "description": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "case_sensitive": {
      "type": "boolean"
    },
    "alphabets": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": [
            "object",
            "string"
          ],
          "patternProperties": {
            "^.*$": {
              "type": [
                "string",
                "array"
              ],
              "maxItems": 2
            }
          }
        }
      }
    }
  },
  "required": [
    "code",
    "title",
    "alphabets"
  ]
}

=== Worthwelle/Alphonic/alphabets/arrl1936.json
{
    "code": "Alphonic-ARRL1936",
    "title": {
        "en": "American Radio Relay League (1936)"
    },
    "description": "The phonetic alphabet used by the American Radio Relay League in 1936.",
    "source": "http://www.tubebooks.org/Books/arrl_1936.pdf",
    "alphabets": {
        "en": {
            "A": "Able",
            "B": "Boy",
            "C": "Cast",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "Have",
            "I": "Item",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Nan",
            "O": "Oboe",
            "P": "Pup",
            "Q": "Quack",
            "R": "Rot",
            "S": "Sail",
            "T": "Tare",
            "U": "Unit",
            "V": "Vice",
            "W": "Watch",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zed"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/lvmpd.json
{
    "code": "LVMPD",
    "title": {
        "en": "Las Vegas Metropolitan Police Department"
    },
    "description": "The phonetic alphabet used by the Las Vegas Metropolitan Police Department, based on the one created by Association of Public-Safety Communications Officials-International.",
    "source": "https://www.lvmpd.com/en-us/ProtectTheCity/Documents/IDF%20Code%20Card.pdf",
    "alphabets": {
        "en": {
            "A": "Adam",
            "B": "Baker",
            "C": "Charlie",
            "D": "David",
            "E": "Easy",
            "F": "Frank",
            "G": "George",
            "H": "Henry",
            "I": "Ida",
            "J": "John",
            "K": "King",
            "L": "Lincoln",
            "M": "Mary",
            "N": "Nora",
            "O": "Ocean",
            "P": "Paul",
            "Q": "Queen",
            "R": "Robert",
            "S": "Sam",
            "T": "Tom",
            "U": "Union",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Yellow",
            "Z": "Zebra"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/apco1941.json
{
    "code": "APCO1941",
    "title": {
        "en": [
            "Association of Public-Safety Communications Officials-International (1941)",
            "Los Angeles Police Department",
            "California Highway Patrol"
        ]
    },
    "description": "",
    "source": "https://archive.org/details/nationaltraining025505mbp",
    "alphabets": {
        "en": {
            "A": "Adam",
            "B": "Boy",
            "C": "Charles",
            "D": "David",
            "E": "Edward",
            "F": "Frank",
            "G": "George",
            "H": "Henry",
            "I": "Ida",
            "J": "John",
            "K": "King",
            "L": "Lincoln",
            "M": "Mary",
            "N": "Nora",
            "O": "Ocean",
            "P": "Paul",
            "Q": "Queen",
            "R": "Robert",
            "S": "Sam",
            "T": "Tom",
            "U": "Union",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Young",
            "Z": "Zebra"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usn1908-2.json
{
    "code": "USN1908-2",
    "title": {
        "en": "U.S. Navy (Version 2)"
    },
    "description": "Used for calling out flags to be hoisted in a signal on the deck of a ship.",
    "source": "https://books.google.com/books?id=dDczAQAAMAAJ&pg=PA82&lpg=PA82&dq=United+States+Navy+General+Signal+Book&source=bl&ots=pUpnCCjDDQ&sig=awa08PCeV1toGpNnqo6CC8tNRLo&hl=en&sa=X&ved=0ahUKEwjn-JP1hJ_ZAhUP42MKHfNVBsAQ6AEILTAB#v=onepage&q=United%20States%20Navy%20General%20Signal%20Book&f=false",
    "alphabets": {
        "en": {
            "A": "Ash",
            "B": "Back",
            "C": "Chain",
            "D": "Dog",
            "E": "Egg",
            "F": "Fox",
            "G": "Gig",
            "H": "Horse",
            "I": "Ice",
            "J": "Jake",
            "K": "King",
            "L": "Lash",
            "M": "Mule",
            "N": "Net",
            "O": "Oak",
            "P": "Page",
            "Q": "Quail",
            "R": "Raft",
            "S": "Scout",
            "T": "Tide",
            "U": "Use",
            "V": "Vast",
            "W": "Winch",
            "X": "Xray",
            "Y": "Yacht",
            "Z": "Zoo"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usn1938.json
{
    "code": "Alphonic-USN1938",
    "title": {
        "en": "U.S. Navy (1938)"
    },
    "description": "The phonetic alphabet used by the U.S. Navy in 1938.",
    "source": "http://www.virhistory.com/navy/manuals/1929_comm_inst-ii.pdf",
    "alphabets": {
        "en": {
            "A": "Afirm",
            "B": "Baker",
            "C": "Cast",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "Hypo",
            "I": "Int",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Negat",
            "O": "Option",
            "P": "Prep",
            "Q": "Queen",
            "R": "Roger",
            "S": "Sail",
            "T": "Tare",
            "U": "Unit",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zed"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usafm2412-1943.json
{
    "code": "Alphonic-USAFM2412-1943",
    "title": {
        "en": "U.S. Army Field Manual 24-12 (1943-1955)"
    },
    "description": "The phonetic alphabet used by the U.S. Army between 1943 and 1955 according to Field Manual 24-12.",
    "source": "https://archive.org/details/SignalBook1916",
    "alphabets": {
        "en": {
            "A": "Able",
            "B": "Baker",
            "C": "Charlie",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "How",
            "I": "Item",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Nan",
            "O": "Oboe",
            "P": "Peter",
            "Q": "Queen",
            "R": "Roger",
            "S": "Sugar",
            "T": "Tare",
            "U": "Uncle",
            "V": "Victor",
            "W": "William",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zed",
            "1": "One",
            "2": "Two",
            "3": "Three",
            "4": "Four",
            "5": "Five",
            "6": "Six",
            "7": "Seven",
            "8": "Eight",
            "9": "Niner",
            "0": "Zero"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/apco1974.json
{
    "code": "APCO1974",
    "title": {
        "en": "Association of Public-Safety Communications Officials-International Project 14(1974)"
    },
    "description": "",
    "source": "https://archive.org/details/nationaltraining025505mbp",
    "alphabets": {
        "en": {
            "A": "Alpha",
            "B": "Bravo",
            "C": "Charlie",
            "D": "Delta",
            "E": "Echo",
            "F": "Foxtrot",
            "G": "Golf",
            "H": "Hotel",
            "I": "India",
            "J": "Juliette",
            "K": "Kilo",
            "L": "Lima",
            "M": "Mike",
            "N": "November",
            "O": "Oscar",
            "P": "Papa",
            "Q": "Quebec",
            "R": "Romeo",
            "S": "Sierra",
            "T": "Tango",
            "U": "Uniform",
            "V": "Victor",
            "W": "Whiskey",
            "X": "Xray",
            "Y": "Yankee",
            "Z": "Zulu"
        }
    }
}

=== Worthwelle/Alphonic/alphabets/usn1927.json
{
    "code": "USN1927",
    "title": {
        "en": "U.S. Navy (1927-1937)"
    },
    "description": "The phonetic alphabet used by the U.S. Navy between 1927 and 1937.",
    "source": "http://www.virhistory.com/navy/manuals/1929_comm_inst-ii.pdf",
    "alphabets": {
        "en": {
            "A": "Afirm",
            "B": "Baker",
            "C": "Cast",
            "D": "Dog",
            "E": "Easy",
            "F": "Fox",
            "G": "George",
            "H": "Hypo",
            "I": "Int",
            "J": "Jig",
            "K": "King",
            "L": "Love",
            "M": "Mike",
            "N": "Negat",
            "O": "Option",
            "P": "Prep",
            "Q": "Quack",
            "R": "Roger",
            "S": "Sail",
            "T": "Tare",
            "U": "Unit",
            "V": "Vice",
            "W": "William",
            "X": "X-ray",
            "Y": "Yoke",
            "Z": "Zed"
        }
    }
}
